# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'exercise-01' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for exercise-01
  pod 'Auth0', '~> 1.26.0'
  pod 'JWTDecode', '~> 2.4.1'

end
